BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "cortex"
BBFILE_PATTERN_cortex = "^${LAYERDIR}/"
BBFILE_PRIORITY_cortex = "20"

LAYERSERIES_COMPAT_cortex = "scarthgap"
