name: Yocto Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  yocto-build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ecofleet-yocto:dev ./docker

      - name: Prepare build config
        run: |
          mkdir -p build-docker/conf
          cp backups/local.conf.working build-docker/conf/local.conf
          cp backups/bblayers.conf.working build-docker/conf/bblayers.conf

      - name: Fix layer paths
        run: |
          sed -i 's#/home/rsmith/cortex-yocto#/work#g' \
            build-docker/conf/bblayers.conf

      - name: Run Yocto build
        env:
          KAS_BUILD_DIR: /home/rsmith/yocto-cache/build
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            -v ${{ github.workspace }}:/work \
            -v /home/rsmith/yocto-cache:/home/rsmith/yocto-cache \
            -w /work \
            -e KAS_BUILD_DIR=/home/rsmith/yocto-cache/build \
            ecofleet-yocto:dev \
            bash -c "kas build kas/dev.yml"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/imx-boot*
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/u-boot*.bin
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/u-boot-spl*.bin
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/Image.gz*
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/*.dtb
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/*.wic.zst
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/*.wic.bmap
            /home/rsmith/yocto-cache/build/tmp/deploy/images/imx8mm-var-dart/*.manifest
